name: Release
jobs:
    build:
        name: build-client
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Install bun
              uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install --production --frozen-lockfile
            - name: Build client
              run: bun run client:build
